/*
 * Defines the REST API used by the React client, including song browsing,
 * authentication, ratings, taste-profile preferences, catalog lookups &
 * personalized recommendations generated by the Python recommender.
 */

import express from "express";
import cors from "cors";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { pool } from "./db";
import { requireAuth, type AuthenticatedRequest } from "./middleware/auth";
import { execFile } from "node:child_process";
import path from "node:path";
import { promisify } from "node:util";
const app = express();

// Convert Node's callback-based execFile helper into a Promise so the
// recommendation route can await the Python process like any other async task.
const execFileAsync = promisify(execFile);

// Allow requests from the local frontend during development and from the
// deployed frontend configured through the CLIENT_URL environment variable.
const allowedOrigins = ["http://localhost:5173", process.env.CLIENT_URL].filter(
  (origin): origin is string => Boolean(origin),
);

app.use(
  cors({
    origin(origin, callback) {
      // Requests without an Origin header, such as server-to-server requests
      // and Supertest integration tests, are allowed.
      if (!origin || allowedOrigins.includes(origin)) {
        return callback(null, true);
      }

      return callback(new Error("Not allowed by CORS"));
    },
  }),
);

app.use(express.json());

// -----------------------------------------------------------------------------
// HEALTH CHECK
// -----------------------------------------------------------------------------

// Simple endpoint used to verify that the API server is running.
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok" });
});

// -----------------------------------------------------------------------------
// SONG BROWSING
// -----------------------------------------------------------------------------

// Return a paginated song catalog with optional title/artist search & genre
// filtering. User-supplied values are passed to PostgreSQL as parameters.
app.get("/api/songs", async (req, res) => {
  try {
    const page = Math.max(Number(req.query.page) || 1, 1);
    const limit = Math.min(Math.max(Number(req.query.limit) || 20, 1), 100);
    const search =
      typeof req.query.search === "string" ? req.query.search.trim() : "";
    const genre =
      typeof req.query.genre === "string" ? req.query.genre.trim() : "";
    const offset = (page - 1) * limit;

    // Build the WHERE clause dynamically while keeping search/filter values
    // separate from the SQL text to avoid directly interpolating user input.
    const whereConditions: string[] = [];
    const values: Array<string | number> = [];
    if (search) {
      values.push(`%${search}%`);
      const searchParam = `$${values.length}`;
      whereConditions.push(`
        (
          s.title ILIKE ${searchParam}
          OR a.name ILIKE ${searchParam}
        )
      `);
    }
    if (genre) {
      values.push(genre);
      const genreParam = `$${values.length}`;
      whereConditions.push(`g.name = ${genreParam}`);
    }
    const whereClause =
      whereConditions.length > 0
        ? `WHERE ${whereConditions.join(" AND ")}`
        : "";

    // Count matching rows first so the frontend receives pagination metadata.
    const countQuery = `
      SELECT COUNT(*)::int AS total
      FROM "Song" s
      JOIN "Artist" a
        ON s."artistId" = a.id
      LEFT JOIN "Genre" g
        ON s."genreId" = g.id
      ${whereClause}
    `;
    const countResult = await pool.query(countQuery, values);
    values.push(limit);
    const limitParam = `$${values.length}`;
    values.push(offset);
    const offsetParam = `$${values.length}`;
    // Fetch only the requested page of songs.
    const songsQuery = `
      SELECT
        s.id,
        s.title,
        s."externalId",
        s."musicBrainzId",
        s."releaseYear",
        s."listenCount",
        s."listenerCount",
        s.popularity,
        s.duration,
        a.name AS artist,
        g.name AS genre
      FROM "Song" s
      JOIN "Artist" a
        ON s."artistId" = a.id
      LEFT JOIN "Genre" g
        ON s."genreId" = g.id
      ${whereClause}
      ORDER BY s.id
      LIMIT ${limitParam}
      OFFSET ${offsetParam}
    `;
    const songsResult = await pool.query(songsQuery, values);
    const total = countResult.rows[0].total;
    const totalPages = Math.ceil(total / limit);
    res.json({
      page,
      limit,
      total,
      totalPages,
      songs: songsResult.rows,
    });
  } catch (error) {
    console.error("Failed to fetch songs:", error);
    res.status(500).json({
      error: "Failed to fetch songs",
    });
  }
});

// -----------------------------------------------------------------------------
// AUTHENTICATION
// -----------------------------------------------------------------------------

// Register a new user, hash their password & issue a seven-day JWT.
app.post("/api/auth/register", async (req, res) => {
  try {
    const { email, username, password } = req.body;
    if (!email || !username || !password) {
      return res.status(400).json({
        error: "Email, username, and password are required",
      });
    }
    if (password.length < 8) {
      return res.status(400).json({
        error: "Password must be at least 8 characters long",
      });
    }
    const existingUser = await pool.query(
      `
      SELECT id
      FROM "User"
      WHERE email = $1 OR username = $2
      LIMIT 1
      `,
      [email, username],
    );
    if (existingUser.rows.length > 0) {
      return res.status(409).json({
        error: "Email or username is already in use",
      });
    }
    // Store only a bcrypt hash; plaintext passwords are never written to the DB.
    const passwordHash = await bcrypt.hash(password, 12);
    const result = await pool.query(
      `
      INSERT INTO "User" (
        email,
        username,
        "passwordHash",
        "updatedAt"
      )
      VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
      RETURNING id, email, username, "createdAt"
      `,
      [email, username, passwordHash],
    );
    const user = result.rows[0];
    const jwtSecret = process.env.JWT_SECRET;
    if (!jwtSecret) {
      throw new Error("JWT_SECRET is not defined");
    }

    // Sign only the user ID into the token, protected routes load account data from the DB.
    const token = jwt.sign(
      {
        userId: user.id,
      },
      jwtSecret,
      {
        expiresIn: "7d",
      },
    );
    return res.status(201).json({
      user,
      token,
    });
  } catch (error) {
    console.error("Failed to register user:", error);
    return res.status(500).json({
      error: "Failed to register user",
    });
  }
});

// Verify an existing user's credentials & issue a fresh JWT.
app.post("/api/auth/login", async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({
        error: "Email and password are required",
      });
    }
    const result = await pool.query(
      `
      SELECT
        id,
        email,
        username,
        "passwordHash",
        "createdAt"
      FROM "User"
      WHERE email = $1
      LIMIT 1
      `,
      [email],
    );
    if (result.rows.length === 0) {
      return res.status(401).json({
        error: "Invalid email or password",
      });
    }
    const user = result.rows[0];

    // Compare the submitted password against the stored bcrypt hash.
    const passwordMatches = await bcrypt.compare(password, user.passwordHash);
    if (!passwordMatches) {
      return res.status(401).json({
        error: "Invalid email or password",
      });
    }
    const jwtSecret = process.env.JWT_SECRET;
    if (!jwtSecret) {
      throw new Error("JWT_SECRET is not defined");
    }

    // Sign only the user ID into the token, protected routes load account data from the DB.
    const token = jwt.sign(
      {
        userId: user.id,
      },
      jwtSecret,
      {
        expiresIn: "7d",
      },
    );
    return res.json({
      user: {
        id: user.id,
        email: user.email,
        username: user.username,
        createdAt: user.createdAt,
      },
      token,
    });
  } catch (error) {
    console.error("Failed to log in:", error);
    return res.status(500).json({
      error: "Failed to log in",
    });
  }
});

// Return the current authenticated user's public account information.
app.get("/api/auth/me", requireAuth, async (req: AuthenticatedRequest, res) => {
  try {
    const result = await pool.query(
      `
        SELECT
          id,
          email,
          username,
          "createdAt"
        FROM "User"
        WHERE id = $1
        `,
      [req.userId],
    );
    if (result.rows.length === 0) {
      return res.status(404).json({
        error: "User not found",
      });
    }
    return res.json({
      user: result.rows[0],
    });
  } catch (error) {
    console.error("Failed to fetch current user:", error);
    return res.status(500).json({
      error: "Failed to fetch current user",
    });
  }
});

// -----------------------------------------------------------------------------
// RATINGS
// -----------------------------------------------------------------------------

// Create a rating/update the user's existing rating for the same song.
app.post(
  "/api/ratings",
  requireAuth,
  async (req: AuthenticatedRequest, res) => {
    try {
      const { songId, value } = req.body;
      if (!songId || !value) {
        return res.status(400).json({
          error: "songId and value are required",
        });
      }
      if (!Number.isInteger(value) || value < 1 || value > 5) {
        return res.status(400).json({
          error: "Rating must be an integer from 1 to 5",
        });
      }
      const songResult = await pool.query(
        `
        SELECT id
        FROM "Song"
        WHERE id = $1
        `,
        [songId],
      );
      if (songResult.rows.length === 0) {
        return res.status(404).json({
          error: "Song not found",
        });
      }
      const result = await pool.query(
        `
        INSERT INTO "Rating" (
          value,
          "userId",
          "songId",
          "updatedAt"
        )
        VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
        -- A user has one current rating per song. Re-rating updates the existing
        -- row instead of creating a duplicate.
        ON CONFLICT ("userId", "songId")
        DO UPDATE SET
          value = EXCLUDED.value,
          "updatedAt" = CURRENT_TIMESTAMP
        RETURNING
          id,
          value,
          "userId",
          "songId",
          "createdAt",
          "updatedAt"
        `,
        [value, req.userId, songId],
      );
      return res.json({
        rating: result.rows[0],
      });
    } catch (error) {
      console.error("Failed to save rating:", error);
      return res.status(500).json({
        error: "Failed to save rating",
      });
    }
  },
);

// Return all ratings owned by the authenticated user.
app.get(
  "/api/ratings/me",
  requireAuth,
  async (req: AuthenticatedRequest, res) => {
    try {
      const result = await pool.query(
        `
        SELECT
          id,
          value,
          "songId",
          "createdAt",
          "updatedAt"
        FROM "Rating"
        WHERE "userId" = $1
        ORDER BY "songId"
        `,
        [req.userId],
      );
      return res.json({
        ratings: result.rows,
      });
    } catch (error) {
      console.error("Failed to fetch ratings:", error);
      return res.status(500).json({
        error: "Failed to fetch ratings",
      });
    }
  },
);

// -----------------------------------------------------------------------------
// TASTE PROFILE PREFERENCES
// -----------------------------------------------------------------------------

// Return the authenticated user's saved favorite genres & artists.
app.get(
  "/api/preferences",
  requireAuth,
  async (req: AuthenticatedRequest, res) => {
    try {
      if (!req.userId) {
        return res.status(401).json({
          error: "Authentication required",
        });
      }
      const genresResult = await pool.query(
        `
        SELECT
          g.id,
          g.name
        FROM "UserFavoriteGenre" ufg
        JOIN "Genre" g
          ON ufg."genreId" = g.id
        WHERE ufg."userId" = $1
        ORDER BY g.name
        `,
        [req.userId],
      );
      const artistsResult = await pool.query(
        `
        SELECT
          a.id,
          a.name
        FROM "UserFavoriteArtist" ufa
        JOIN "Artist" a
          ON ufa."artistId" = a.id
        WHERE ufa."userId" = $1
        ORDER BY a.name
        `,
        [req.userId],
      );
      return res.json({
        genres: genresResult.rows,
        artists: artistsResult.rows,
      });
    } catch (error) {
      console.error("Failed to fetch preferences:", error);
      return res.status(500).json({
        error: "Failed to fetch preferences",
      });
    }
  },
);

// Replace the user's saved genres & artists as one atomic update.
app.put(
  "/api/preferences",
  requireAuth,
  async (req: AuthenticatedRequest, res) => {
    const client = await pool.connect();
    try {
      if (!req.userId) {
        return res.status(401).json({
          error: "Authentication required",
        });
      }
      const { genreIds, artistIds } = req.body;
      if (!Array.isArray(genreIds) || !Array.isArray(artistIds)) {
        return res.status(400).json({
          error: "genreIds and artistIds must be arrays",
        });
      }

      // Normalize IDs to numbers & remove duplicate selections before validation.
      const normalizedGenreIds = [...new Set(genreIds.map(Number))];
      const normalizedArtistIds = [...new Set(artistIds.map(Number))];
      const invalidGenreId = normalizedGenreIds.some(
        (id) => !Number.isInteger(id) || id <= 0,
      );
      const invalidArtistId = normalizedArtistIds.some(
        (id) => !Number.isInteger(id) || id <= 0,
      );
      if (invalidGenreId || invalidArtistId) {
        return res.status(400).json({
          error: "Preference IDs must be positive integers",
        });
      }
      // Keep the entire preference replacement atomic. Any validation/write
      // failure rolls the transaction back to the user's previous selections.
      await client.query("BEGIN");
      if (normalizedGenreIds.length > 0) {
        const genreCheck = await client.query(
          `
          SELECT id
          FROM "Genre"
          WHERE id = ANY($1::int[])
          `,
          [normalizedGenreIds],
        );
        if (genreCheck.rows.length !== normalizedGenreIds.length) {
          await client.query("ROLLBACK");
          return res.status(400).json({
            error: "One or more genre IDs are invalid",
          });
        }
      }
      if (normalizedArtistIds.length > 0) {
        const artistCheck = await client.query(
          `
          SELECT id
          FROM "Artist"
          WHERE id = ANY($1::int[])
          `,
          [normalizedArtistIds],
        );
        if (artistCheck.rows.length !== normalizedArtistIds.length) {
          await client.query("ROLLBACK");
          return res.status(400).json({
            error: "One or more artist IDs are invalid",
          });
        }
      }

      // Replace the old selections rather than trying to diff individual rows.
      await client.query(
        `
        DELETE FROM "UserFavoriteGenre"
        WHERE "userId" = $1
        `,
        [req.userId],
      );
      await client.query(
        `
        DELETE FROM "UserFavoriteArtist"
        WHERE "userId" = $1
        `,
        [req.userId],
      );
      for (const genreId of normalizedGenreIds) {
        await client.query(
          `
          INSERT INTO "UserFavoriteGenre" (
            "userId",
            "genreId"
          )
          VALUES ($1, $2)
          `,
          [req.userId, genreId],
        );
      }
      for (const artistId of normalizedArtistIds) {
        await client.query(
          `
          INSERT INTO "UserFavoriteArtist" (
            "userId",
            "artistId"
          )
          VALUES ($1, $2)
          `,
          [req.userId, artistId],
        );
      }
      await client.query("COMMIT");
      const genresResult = await pool.query(
        `
        SELECT
          g.id,
          g.name
        FROM "UserFavoriteGenre" ufg
        JOIN "Genre" g
          ON ufg."genreId" = g.id
        WHERE ufg."userId" = $1
        ORDER BY g.name
        `,
        [req.userId],
      );
      const artistsResult = await pool.query(
        `
        SELECT
          a.id,
          a.name
        FROM "UserFavoriteArtist" ufa
        JOIN "Artist" a
          ON ufa."artistId" = a.id
        WHERE ufa."userId" = $1
        ORDER BY a.name
        `,
        [req.userId],
      );
      return res.json({
        genres: genresResult.rows,
        artists: artistsResult.rows,
      });
    } catch (error) {
      await client.query("ROLLBACK");
      console.error("Failed to update preferences:", error);
      return res.status(500).json({
        error: "Failed to update preferences",
      });
    } finally {
      client.release();
    }
  },
);

// -----------------------------------------------------------------------------
// CATALOG LOOKUPS
// -----------------------------------------------------------------------------

// Return all genres used by browse filters & taste-profile selector.
app.get("/api/genres", async (_req, res) => {
  try {
    const result = await pool.query(
      `
      SELECT
        id,
        name
      FROM "Genre"
      ORDER BY name
      `,
    );
    return res.json({
      genres: result.rows,
    });
  } catch (error) {
    console.error("Failed to fetch genres:", error);
    return res.status(500).json({
      error: "Failed to fetch genres",
    });
  }
});

// Search artists by name for the taste-profile artist picker.
app.get("/api/artists", async (req, res) => {
  try {
    const search =
      typeof req.query.search === "string" ? req.query.search.trim() : "";
    const limitValue =
      typeof req.query.limit === "string" ? Number(req.query.limit) : 50;
    const limit = Number.isInteger(limitValue)
      ? Math.min(Math.max(limitValue, 1), 100)
      : 50;
    const values: unknown[] = [];

    // Build an optional parameterized name search & cap the result size.
    let query = `
      SELECT
        id,
        name
      FROM "Artist"
    `;
    if (search) {
      values.push(`%${search}%`);
      query += `
        WHERE name ILIKE $${values.length}
      `;
    }
    values.push(limit);
    query += `
      ORDER BY name
      LIMIT $${values.length}
    `;
    const result = await pool.query(query, values);
    return res.json({
      artists: result.rows,
    });
  } catch (error) {
    console.error("Failed to fetch artists:", error);
    return res.status(500).json({
      error: "Failed to fetch artists",
    });
  }
});

// -----------------------------------------------------------------------------
// RECOMMENDATIONS
// -----------------------------------------------------------------------------

// Run the Python recommendation engine for the authenticated user & return
// the generated JSON response to the frontend.
app.get(
  "/api/recommendations",
  requireAuth,
  async (req: AuthenticatedRequest, res) => {
    try {
      if (!req.userId) {
        return res.status(401).json({
          error: "Authentication required",
        });
      }
      // The backend is normally started from /server, so the repository root is
      // one directory above the current working directory.
      const projectRoot = path.resolve(process.cwd(), "..");

      // Use the recommender virtual environment so Python dependencies are
      // isolated from the system installation.
      // Use an explicitly configured Python executable in production.
      // Local development falls back to the recommender virtual environment.
      const pythonPath =
        process.env.PYTHON_EXECUTABLE ??
        path.join(projectRoot, "recommender", ".venv", "bin", "python");

      const recommenderPath = path.join(
        projectRoot,
        "recommender",
        "src",
        "preprocessing",
        "recommend.py",
      );

      // Pass the authenticated user ID to recommend.py & capture its JSON output.
      const { stdout } = await execFileAsync(
        pythonPath,
        [recommenderPath, String(req.userId)],
        {
          cwd: projectRoot,
        },
      );

      // recommend.py prints one JSON object to stdout for this route to forward.
      const data = JSON.parse(stdout.trim());
      return res.json(data);
    } catch (error) {
      console.error("Failed to generate recommendations:", error);
      return res.status(500).json({
        error: "Failed to generate recommendations",
      });
    }
  },
);

// Export without calling listen() so tests can import the configured app
// without starting a real server. index.ts is responsible for app.listen().
export default app;
